#!/bin/bash

. $(dirname $0)/binary-repo-lib.sh

#modfiles=$(git diff-tree -r --name-status $GIT_COMMIT | awk '$1 != "D" { print $2 }')
modfiles=$(git ls-files | grep '\.jar$')
user=user
password=password

printInfo() {
  echo ""
  echo "Arguments $@"
  echo "GIT_DIR = $GIT_DIR"
  echo "GIT_WORK_TREE = $GIT_WORK_TREE"
  echo "GIT_INDEX_TREE = $GIT_INDEX_FILE"
  echo "GIT_COMMIT = $GIT_COMMIT"
  echo "Changes"
  echo "-----------"
  echo "$modfiles"
  echo "-----------"
}

# Fix whitespace in source
for file in $(git ls-files src sources | egrep '\.(java|scala)$'); do
  sed -i "" '/[ 	
]*$/ s///' "$file"
done

# Remove jar files
jarfiles=$(git ls-files | grep '\.jar$')
for file in $jarfiles; do
  if test -f $file; then
    p=$(pwd)
    pushJarFile "$p/$file" "$p" "$user" "$password"
    rm -f $file
  fi
done

# Copy utility scripts into EVERY COMMIT.  This way, there' always available for recovering JAR Files.
cp -R $(dirname $0)/first-commit/* .

exit 0

